MusicEventAPI/Areas/Admin/Controllers/MainCategoryController.cs
using MusicEventAPI.Areas.Admin.Entity;
using MusicEventAPI.Areas.Admin.Models;
using MusicEventAPI.Areas.Admin.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicEventAPI.Areas.Admin.Controllers
{
    public class MainCategoryController : Controller
    {
        private MainCategoryRepository repository = new MainCategoryRepository();
        // GET: Admin/Category
        public ActionResult Index()
        {
            if (CheckAdminAccess.CheckAdmin())
                return RedirectToAction("", "Login", new { Area = "Admin" });
            return View();
        }

        public ActionResult loaddata(int status)
        {
            List<Admin_MainGetCategoryList_Result> data = repository.GetCategory(status);
            return Json(new { data = data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Manage(int id = 0)
        {
            if (CheckAdminAccess.CheckAdmin())
                return RedirectToAction("", "Login", new { Area = "Admin" });

            if (id == 0)
            {
                MainCategory model = new MainCategory();
                return View(model);
            }
            else
            {
                MainCategory model = repository.GetCategoryDetail(id);
                if (model == null)
                    return HttpNotFound();
                return View(model);
            }

        }



        [HttpPost]
        public ActionResult Manage(MainCategory model)
        {
            if (CheckAdminAccess.CheckAdmin())
                return RedirectToAction("", "Login", new { Area = "Admin" });
            string msg = (model.MainCatID == 0 ? "Add" : "Updated");
            model = repository.ManageCategory(model);
            if (model.MainCatID > 0 && model.MainCatID != -1)
            {
                TempData["message"] = "Sub Category " + msg + " Successfully.";
                TempData["class"] = "alert alert-success";
                return RedirectToAction("Index");
            }
            else
                TempData["ErrorMessage"] = "Please try again.";

            return View(model);
        }

    }
}

MusicEventAPI/Areas/Admin/Views/MainCategory/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_master.cshtml";
    if (TempData["message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                var seconds = 5;
                setTimeout(function () {
                    document.getElementById("lblmessage").style.display = "none";
                }, seconds * 1000);
            };
        </script>
    }
}
<style>
    form#myformid {
        float: left;
        width: 100%;
        padding: 15px;
    }

    .radio-list label input {
        float: left;
    }

    .no-space label input {
        float: left;
    }

    .panel-collapse {
        padding: 10px;
    }
</style>

<link href="../../AdminLTE/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="../../AdminLTE/plugins/datatables/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="../../AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="../../AdminLTE/plugins/datatables/dataTables.bootstrap.min.js"></script>

<section class="content-header">
    <h1>
        Category Group
        @*<small>Version 2.0</small>*@
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Admin/MainCategory"><i class="fa fa-dashboard"></i>Category Group</a></li>
    </ol>
</section>
<!-- Main content -->
<section class="content">

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    <div class="row">
        @if (TempData["message"] != null)
        {
            <div class="col-md-12 no-space" role="alert" id="lblmessage">
                <div class='@TempData["class"]'><strong>@TempData["message"]</strong></div>
            </div>
        }
        <div class="col-xs-12">

            <div class="box">
                <div class="box-header">
                    @*<h3 class="box-title">Display Testimonial</h3>*@
                </div>
                <div class="box-body">
                    @Html.Partial("~/Areas/Admin/Views/MainCategory/_SubCategory.cshtml")
                </div>
            </div>
        </div>
    </div>

</section>

MusicEventAPI/Areas/Admin/Views/MainCategory/Manage.cshtml
@model MusicEventAPI.Areas.Admin.Entity.MainCategory
@{
    ViewBag.Title = "Manage";
    Layout = "~/Areas/Admin/Views/Shared/_master.cshtml";
    if (TempData["message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                var seconds = 5;
                setTimeout(function () {
                    document.getElementById("lblmessage").style.display = "none";
                }, seconds * 1000);
            };
        </script>
    }
}
<style>
    form#myformid {
        float: left;
        width: 100%;
        padding: 15px;
    }

    .radio-list label input {
        float: left;
    }

    .no-space label input {
        float: left;
    }

    .astricred {
        color: red;
        font-size: 17px;
    }

    .panel-collapse {
        padding: 10px;
    }
</style>



<section class="content-header">
    @if (Model.MainCatID == 0)
    {<h1>Add Category Group<small></small></h1>
    }
    else
    {
        <h1>Edit Category Group <small></small></h1>
    }
    <ol class="breadcrumb">
        <li><a href="/Admin/MainCategory"><i class="fa fa-dashboard"></i> Category Group</a></li>
        <li class="active">Manage</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <link href="../../css/jquery-ui.css" rel="stylesheet" />
    <link href="../../css/hint-tooltip.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")

    @{
        List<SelectListItem> listItems3 = new List<SelectListItem>();
        {

            listItems3.Add(new SelectListItem
            {
                Text = "1",
                Value = "1"
            });
            listItems3.Add(new SelectListItem
            {
                Text = "2",
                Value = "2"
            });
            listItems3.Add(new SelectListItem
            {
                Text = "3",
                Value = "3"
            });
            listItems3.Add(new SelectListItem
            {
                Text = "4",
                Value = "4"

            });
            listItems3.Add(new SelectListItem
            {
                Text = "5",
                Value = "5"
            });


        }
    }
    @if (TempData["SuccessMessage"] != null)
    {
        <div class="col-md-12 no-space" role="alert" id="lblmessage">
            <div class='@TempData["SuccessMessage"]'><strong>@TempData["SuccessMessage"]</strong></div>
        </div>
    }

    <div class="box box-primary">

        <div class="box-body">
            @using (Html.BeginForm("Manage", "MainCategory", FormMethod.Post, new { enctype = "multipart/form-data", @id = "testimonial_form" }))
            {
                @*<form role="form" action="#">*@
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="col-md-6">
                    <div class="col-md-12">
                        <div class="form-group" style="margin-left: 12px;">
                            <b>Category Group Name</b><span class="astricred">*</span>
                            @Html.HiddenFor(x => x.MainCatID)
                            @Html.TextBoxFor(model => model.MainCategoryName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(o => o.MainCategoryName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-12" style="margin-left: 15px;">
                        <div class="checkbox">
                            <label>@Html.CheckBoxFor(x => x.IsActive) <strong> Is Active</strong></label>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="button" onclick="javascript:history.back()" class="btn btn-default pull-right">Cancel</button>
                        <button type="submit" style="margin-right: 10px;" class="btn btn-success pull-right">@(Model.MainCatID == 0 ? "Create" : "Update")</button>
                        <button type="submit" id="btnsubmitcall" style="display:none"></button>
                    </div>
                </div>
                    <div class="col-md-12">


                    </div>
            }
        </div>
    </div>
    <script src="../../Scripts/jquery-1.10.2.js"></script>
    <script src="../../JS/jquery-ui.js"></script>

</section>
<script>

    $("#btnsubmit").click(function () {
        var categoryName = $("#MainCategoryName").val();

        if (categoryName == "") {
            swal("Error!", "Please Enter Category Group Name.", "error")
        }
        else {
            $("#btnsubmitcall").click();
        }
    })
</script>

MusicEventAPI/Areas/Admin/Views/MainCategory/_SubCategory.cshtml
<div class="row">
    <div class="col-md-12">
        @{
            List<SelectListItem> listItems3 = new List<SelectListItem>();
            {
                listItems3.Add(new SelectListItem
                {
                    Text = "All",
                    Value = "0",
                    Selected = true
                });
                listItems3.Add(new SelectListItem
                {
                    Text = "Active",
                    Value = "1"
                });
                listItems3.Add(new SelectListItem
                {
                    Text = "In-Active",
                    Value = "2"
                });


            }
        }
        <div class="col-md-6">
            <div class="">
                <strong>Status</strong>   @Html.DropDownList("ddlrole", listItems3, new { @class = "form-control", id = "ddlrole" })
            </div>
        </div>

        <div class="col-md-6">
            <button type="button" class="btn btn-primary" onclick="return addCategory();">Create Category Group</button>

        </div>
    </div>
</div>
<table class="table  table-responsive table-bordered" id="tbltestimonial">
    <thead>
        <tr>
            <th>GroupID</th>
            <th>Name</th>
            <th>Active</th>
            <th align="center">Edit</th>
        </tr>
    </thead>
</table>

<script type="text/javascript">
    var $tbltestimonialtab = null;
    $(document).ready(function () {

        $tbltestimonialtab = $('#tbltestimonial').DataTable({

            "ajax": {
                "url": "/Admin/MainCategory/loaddata",
                "type": "GET",
                "datatype": "json",
                "data": function (d) {
                    d.status = $("#ddlrole").val();
                }
                //"data": $("#hdnUserID").val()
            },
            "bLengthChange": false,
            "columns": [

                    { "data": "CategoryUniqueID", "autoWidth": true },
                    { "data": "MainCategoryName", "autoWidth": true },
                    {

                        "aTargets": [2], "sName": "", "bSortable": false, "sClass": "centerc",
                        "render": function (data, type, row) {
                            return row.ISActive == true ? '<i class="fa fa-check"></i>' : '<i class="fa fa-times"></i>'
                        }
                    },

                       {
                           "aTargets": [3], "sName": "", "bSortable": false, "sClass": "centerc",
                           "render": function (data, type, row) {
                               return '<a onclick="return edit(' + row.MainCatID + ');" title="Edit"> <i class="glyphicon glyphicon-edit"></i> </a>'
                           }
                       }

            ],
            "language": {
                "emptyTable": "<div class='row'><div class='col-md-12'><div class='alert alert-danger'><p><strong>No record found.</strong></p> </div></div>"
            }
        });
    });
    function edit(id) {
        window.location.href = '/Admin/MainCategory/Manage?id=' + id + '';
    }
    //$(document).delegate(".clsremovetest", "click", function () {
    //    var id = $(this).attr("data-PartNerID");
    //    if (confirm('Are you sure to remove this Partner?')) {
    //        window.location.href = '/Manage/Partners/DeletePartners?id=' + id + '';
    //    }
    //})
    $("#ddlrole").change(function () {

        $tbltestimonialtab.ajax.reload();
    })
    function addCategory() {
        window.location.href = '/Admin/MainCategory/Manage';
    }
</script>